
exports.handler = async (event, context) => {
  // Set CORS headers
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  };

  // Handle preflight requests
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers,
      body: '',
    };
  }

  try {
    // Parse the request body if it exists
    const body = event.body ? JSON.parse(event.body) : {};
    
    console.log('Generate Article function called with:', body);

    // Your article generation logic would go here
    // For now, returning a sample response
    const generatedArticle = {
      title: "Sample Generated Article",
      content: "This is a sample article generated by the Netlify function.",
      timestamp: new Date().toISOString(),
      requestData: body
    };

    return {
      statusCode: 200,
      headers: {
        ...headers,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(generatedArticle),
    };
  } catch (error) {
    console.error('Error in generateArticle function:', error);
    
    return {
      statusCode: 500,
      headers: {
        ...headers,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        error: 'Internal server error',
        message: error.message,
      }),
    };
  }
};
